/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Bruno
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUsuarioCadastrar = new javax.swing.JMenuItem();
        jMenuItemDisciplinaCadastrar = new javax.swing.JMenuItem();
        jMenuItemTurmaCadastrar = new javax.swing.JMenuItem();
        jMenuItemUsuarioTurmaCadastrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemUsuariosListar = new javax.swing.JMenuItem();
        jMenuItemDisciplinasListar = new javax.swing.JMenuItem();
        jMenuItemTurmasListar = new javax.swing.JMenuItem();
        jMenuItemUsuariosTurmasListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setText("ADM");
        jLabel1.setToolTipText("");

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setToolTipText("");

        jMenu1.setText("Cadastrar");

        jMenuItemUsuarioCadastrar.setText("Usuário");
        jMenuItemUsuarioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuarioCadastrar);

        jMenuItemDisciplinaCadastrar.setText("Disciplina");
        jMenuItemDisciplinaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisciplinaCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDisciplinaCadastrar);

        jMenuItemTurmaCadastrar.setText("Turma");
        jMenuItemTurmaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurmaCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTurmaCadastrar);

        jMenuItemUsuarioTurmaCadastrar.setText("Usuário Turma");
        jMenuItemUsuarioTurmaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioTurmaCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuarioTurmaCadastrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");

        jMenuItemUsuariosListar.setText("Usuários");
        jMenuItemUsuariosListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosListarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUsuariosListar);

        jMenuItemDisciplinasListar.setText("Disciplinas");
        jMenuItemDisciplinasListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisciplinasListarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDisciplinasListar);

        jMenuItemTurmasListar.setText("Turmas");
        jMenuItemTurmasListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurmasListarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTurmasListar);

        jMenuItemUsuariosTurmasListar.setText("Usuários Turmas");
        jMenuItemUsuariosTurmasListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosTurmasListarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUsuariosTurmasListar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioTurmaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioTurmaCadastrarActionPerformed
        FrmUsuarioTurma tela = new FrmUsuarioTurma();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemUsuarioTurmaCadastrarActionPerformed

    private void jMenuItemUsuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioCadastrarActionPerformed
        FrmUsuario tela = new FrmUsuario();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemUsuarioCadastrarActionPerformed

    private void jMenuItemDisciplinaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisciplinaCadastrarActionPerformed
        FrmDisciplina tela = new FrmDisciplina();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemDisciplinaCadastrarActionPerformed

    private void jMenuItemTurmaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurmaCadastrarActionPerformed
        FrmTurma tela = new FrmTurma();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemTurmaCadastrarActionPerformed

    private void jMenuItemUsuariosListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosListarActionPerformed
        ListUsuario tela = new ListUsuario();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemUsuariosListarActionPerformed

    private void jMenuItemDisciplinasListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisciplinasListarActionPerformed
        ListDisciplina tela = new ListDisciplina();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemDisciplinasListarActionPerformed

    private void jMenuItemTurmasListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurmasListarActionPerformed
        ListTurma tela = new ListTurma();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemTurmasListarActionPerformed

    private void jMenuItemUsuariosTurmasListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosTurmasListarActionPerformed
        ListUsuariosTurma tela = new ListUsuariosTurma();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemUsuariosTurmasListarActionPerformed
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDisciplinaCadastrar;
    private javax.swing.JMenuItem jMenuItemDisciplinasListar;
    private javax.swing.JMenuItem jMenuItemTurmaCadastrar;
    private javax.swing.JMenuItem jMenuItemTurmasListar;
    private javax.swing.JMenuItem jMenuItemUsuarioCadastrar;
    private javax.swing.JMenuItem jMenuItemUsuarioTurmaCadastrar;
    private javax.swing.JMenuItem jMenuItemUsuariosListar;
    private javax.swing.JMenuItem jMenuItemUsuariosTurmasListar;
    // End of variables declaration//GEN-END:variables
}
