/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import dao.AvaliacaoDAO;
import dao.TurmaDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.Avaliacao;
import model.Turma;
/**
 *
 * @author User
 */
public class AvaliacaoView extends javax.swing.JFrame {

    /**
     * Creates new form Avaliacao
     */
    public AvaliacaoView() {
        initComponents();
        carregaTurma();
    }
private void carregaTurma(){
List<Turma> listaturma = TurmaDAO.getTurmas();
        DefaultComboBoxModel model = 
                new DefaultComboBoxModel();
        for(Turma turma : listaturma){
            model.addElement(turma);
        
        }
        TurmaCombo.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeAv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TurmaCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeAv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAvActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        TurmaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurmaComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Turma");

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TurmaCombo, 0, 137, Short.MAX_VALUE)
                            .addComponent(NomeAv)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(Salvar)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addComponent(Salvar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeAvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAvActionPerformed

    private void TurmaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurmaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TurmaComboActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        Avaliacao avaliacao = new Avaliacao();
        
        String nome = NomeAv.getText();
        Turma turma = (Turma) TurmaCombo.getSelectedItem();
        avaliacao.setNome(nome);
        avaliacao.setTurma(turma);
        AvaliacaoDAO.inserir(avaliacao);
    }//GEN-LAST:event_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeAv;
    private javax.swing.JButton Salvar;
    private javax.swing.JComboBox<String> TurmaCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
