/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DisciplinaDAO;
import dao.TurmaDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Disciplina;
import model.Turma;

/**
 *
 * @author Bruno
 */
public class FrmTurma extends javax.swing.JFrame {

    private Turma turma;
    
    /**
     * Creates new form FrmTurma
     */
    public FrmTurma() {
        initComponents();
        carregarDisciplinas();
    }
    
    public FrmTurma(int idTurma) {
        initComponents();
        carregarFormulario(idTurma);
        carregarDisciplinas();
    }
    
    private void carregarFormulario(int idTurma){
        turma = TurmaDAO.getTurmaById( idTurma );
        txtNome.setText(turma.getNome());
        
        List<Turma> listaTurmas = TurmaDAO.getTurmas();
        for(int i = 0; i<listaTurmas.size(); i++){
            if (listaTurmas.get(i).getId() == turma.getDisciplina().getId()){
                cmbDisciplina.setSelectedIndex( i + 1 );
                break;
            }
        }      
    }
    
    private void limpar() {
        txtNome.setText("");
        cmbDisciplina.setSelectedIndex( 0 );
        
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        cmbDisciplina = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Turma");
        setResizable(false);

        jLabel1.setText("Nome:");

        jLabel2.setText("Disciplina:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cmbDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNome)
                        .addComponent(cmbDisciplina, 0, 160, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void carregarDisciplinas(){
        List<Disciplina> listaDisciplinas = DisciplinaDAO.getDisciplinas();
             
        DefaultComboBoxModel model = 
                new DefaultComboBoxModel();
        Disciplina fake = new Disciplina();
        fake.setId(0);
        fake.setNome("Selecione...");
        model.addElement(fake); 
        
        for (Disciplina disciplina : listaDisciplinas) {
            model.addElement( disciplina );
        }
        cmbDisciplina.setModel( model );
        
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNome.getText();
        Disciplina disc = (Disciplina) cmbDisciplina.getSelectedItem();
        String erro = "";
        if( nome.isEmpty() ){
            erro += "Nome\n";
        }
        if( ! erro.isEmpty() ){
            JOptionPane.showMessageDialog(this, 
                "Você esqueceu de preencher:\n" 
                + erro );
        }else{
            if(turma == null){
                Turma turma = new Turma();
                turma.setNome( nome );
                turma.setDisciplina( disc );
                TurmaDAO.inserir( turma );
                limpar();
            }else{
                turma.setNome( nome );
                turma.setDisciplina( disc );
                TurmaDAO.editar( turma );
            }
            this.dispose();
        }
        limpar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
