/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import dao.UsuarioDAO;
import dao.TurmaDAO;
import dao.UsuarioTurmaDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Usuario;
import model.Turma;
import model.UsuarioTurma;

/**
 *
 * @author 631420395
 */
public class FrmUsuarioTurma extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuarioTurma
     */
    public FrmUsuarioTurma() {
        initComponents();
        carregarTurmas();
        carregarUsuarios();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbUsuario = new javax.swing.JComboBox<>();
        cmbTurma = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Usuários para Turma");

        jLabel1.setText("Usuário:");

        jLabel2.setText("Turma:");

        cmbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        cmbTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbTurma, 0, 143, Short.MAX_VALUE)
                    .addComponent(cmbUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpar() {
        cmbUsuario.setSelectedIndex( 0 );
    }
    
    private void carregarTurmas(){
        List<Turma> listaTurmas = TurmaDAO.getTurmas();
             
        DefaultComboBoxModel model = 
                new DefaultComboBoxModel();
        Turma fake = new Turma();
        fake.setId(0);
        fake.setNome("Selecione...");
        model.addElement(fake); 
        
        for (Turma turma : listaTurmas) {
            model.addElement( turma );
        }
        cmbTurma.setModel( model );
        
    }
    
    private void carregarUsuarios(){
        List<Usuario> listaUsuarios = UsuarioDAO.getUsuarios();
             
        DefaultComboBoxModel model = 
                new DefaultComboBoxModel();
        Usuario fake = new Usuario();
        fake.setId(0);
        fake.setNome("Selecione...");
        model.addElement(fake); 
        
        for (Usuario usuario : listaUsuarios) {
            model.addElement( usuario );
        }
        cmbUsuario.setModel( model );
        
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Turma turma = (Turma) cmbTurma.getSelectedItem();
        Usuario usuario = (Usuario) cmbUsuario.getSelectedItem();
        UsuarioTurma usutur = new UsuarioTurma();
        usutur.setTurma( turma );
        usutur.setUsuario( usuario );
        UsuarioTurmaDAO.inserir( usutur );
        limpar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTurma;
    private javax.swing.JComboBox<String> cmbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
